In [134]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import metrics, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.decomposition import PCA, KernelPCA
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

%matplotlib inline

# 1- Dividing wines into three classes

## 1.1- Exploratory data analysis

### 1.1.1- Red wine

In [3]:
# Read data with read_csv method of the pandas library.
bankdata_red = pd.read_csv("data/new_format/winequality-red-classes.csv", sep = ',')
# see the rows and columns of the data
bankdata_red.shape

(1599, 12)

In [4]:
# get a feel of how our dataset actually looks
bankdata_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol   class  
0      9.4  medium  
1      9.8  medium  
2      9.8  medium  
3      9.8  medium  
4      9.4  medium

In [5]:
# view some basic statistical details like percentile, mean, std etc.
bankdata_red.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol  
count  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983  
std       0.154386     0.169507     1.065668  
min       2.740000     0.330000     8.400000  
25%       3.210000     0.550000     9.500000  
50%       3.310000     0.620000    10.200000  
75%       3.400000     0.730000    11.100000  
max       4.010000     2.000000    14.900000

### 1.1.2- White wine

In [6]:
# Read data with read_csv method of the pandas library.
bankdata_white = pd.read_csv("data/new_format/winequality-white-classes.csv", sep = ',')
# see the rows and columns of the data
bankdata_white.shape

(4898, 12)

In [7]:
# get a feel of how our dataset actually looks
bankdata_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol   class  
0      8.8  medium  
1      9.5  medium  
2     10.1  medium  
3      9.9  medium  
4      9.9  medium

In [8]:
# view some basic statistical details like mean, std etc.
bankdata_white.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol  
count  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267  
std       0.151001     0.114126     1.230621  
min       2.720000     0.220000     8.000000  
25%       3.090000     0.410000     9.500000  
50%       3.180000     0.470000    10.400000  
75%       3.280000     0.550000    11.400000  
max       3.820000     1.080000    14.200000

## 1.2- Data preprocessing

Data preprocessing involves (1) Dividing the data into attributes and labels and (2) dividing the data into training and testing sets

### 1..2.1- Split dataset in train and test

#### 1.2.1.1- Red wine

In [9]:
# In the first line of the script above, all the columns of the bankdata dataframe 
#are being stored in the X variable except the "quality" column, which is the label column. 
#The drop() method drops this column.
X_red = bankdata_red.drop('class', axis=1)
y_red = bankdata_red['class']
y_red.head()

0    medium
1    medium
2    medium
3    medium
4    medium
Name: class, dtype: object

Once the data is divided into attributes and labels, the final preprocessing step is to divide data into training and test sets. 

In [10]:
# divide data into training and test sets.
X_train_red, X_test_red, y_train_red, y_test_red = train_test_split(X_red, y_red, test_size = 0.20)

X_train_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1568            7.0              0.56         0.13             1.6      0.077   
163             7.4              0.60         0.26             7.3      0.070   
1256            7.5              0.59         0.22             1.8      0.082   
117             7.8              0.56         0.12             2.0      0.082   
1266            7.2              0.57         0.05             2.3      0.081   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1568                 25.0                  42.0  0.99629  3.34       0.59   
163                  36.0                 121.0  0.99820  3.37       0.49   
1256                 43.0                  60.0  0.99499  3.10       0.42   
117                   7.0                  28.0  0.99700  3.37       0.50   
1266                 16.0                  36.0  0.99564  3.38       0.60   

      alcohol  
1568      9.2  
163       9.4  
1256      9.2  
117       9.4  
1266     10.3

In [11]:
y_train_red.head()

1568    medium
163     medium
1256    medium
117     medium
1266    medium
Name: class, dtype: object

#### 1.2.1.2- White wine

In [12]:
# In the first line of the script above, all the columns of the bankdata dataframe 
#are being stored in the X variable except the "quality" column, which is the label column. 
#The drop() method drops this column.
X_white = bankdata_white.drop('class', axis=1)
y_white = bankdata_white['class']

In [13]:
# divide data into training and test sets.
X_train_white, X_test_white, y_train_white, y_test_white = train_test_split(X_white, y_white, test_size = 0.20)

In [14]:
X_train_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
2532            6.7             0.540         0.27             7.1      0.049   
4285            6.0             0.200         0.26             6.8      0.049   
4264            5.8             0.200         0.16             1.4      0.042   
4470            4.7             0.145         0.29             1.0      0.042   
3314            6.6             0.435         0.38             9.2      0.058   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
2532                  8.0                 178.0  0.99502  3.16       0.38   
4285                 22.0                  93.0  0.99280  3.15       0.42   
4264                 44.0                  99.0  0.98912  3.23       0.37   
4470                 35.0                  90.0  0.99080  3.76       0.49   
3314                 66.0                 243.0  0.99833  3.23       0.54   

      alcohol  
2532      9.4  
4285     11.0  
4264     12.2  
4470     11.3  
3314      9.1

In [81]:
y_train_white.head()

2532       low
4285    medium
4264    medium
4470    medium
3314    medium
Name: class, dtype: object

### 1.2.2- Data standarization

Standarization of datasets is a common requirement for many machine learning estimators. They might behave badly if the individual features do not more or less look like standard normally distributed data: Gaussian with zero mean and unit variance.

Here we are going to use StandardScaler, that standardize features by removing the mean and scaling to unit variance. The standard score of a sample $x$ is calculated as:

$x_{scaled} = \dfrac{x - \mu}{\sigma}$

where $\mu$ is the mean of the training samples and $\sigma$ is the standard deviation of the training samples.

#### 1.2.2.1- Red wine

In [82]:
X_train_red_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_train_red), columns=X_train_red.columns.values)
X_train_red_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.760650          0.193844    -0.752391       -0.690005  -0.220919   
1      -0.530589          0.416275    -0.079593        3.621041  -0.359835   
2      -0.473074          0.360668    -0.286608       -0.538740  -0.121693   
3      -0.300528          0.193844    -0.804145       -0.387476  -0.121693   
4      -0.645619          0.249452    -1.166421       -0.160578  -0.141538   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.862306             -0.143972 -0.238748  0.176682  -0.399161   
1             1.909142              2.256528  0.771182  0.367595  -0.975832   
2             2.575311              0.402978 -0.926134 -1.350616  -1.379502   
3            -0.850699             -0.569376  0.136671  0.367595  -0.918165   
4             0.005804             -0.326288 -0.582441  0.431232  -0.341494   

    alcohol  
0 -1.135697  
1 -0.949581  
2 -1.135697  
3 -0.949581  
4 -0.112060

In [86]:
X_train_red_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   1.279000e+03      1.279000e+03  1.279000e+03    1.279000e+03   
mean   -2.451345e-16      1.916632e-16  1.111091e-16    3.402716e-17   
std     1.000391e+00      1.000391e+00  1.000391e+00    1.000391e+00   
min    -2.141018e+00     -2.252896e+00 -1.425189e+00   -1.219432e+00   
25%    -7.031348e-01     -7.514869e-01 -9.076521e-01   -4.631079e-01   
50%    -2.430123e-01     -2.858646e-02 -7.959305e-02   -2.362107e-01   
75%     5.046867e-01      6.109024e-01  7.484660e-01    6.631878e-02   
max     4.358213e+00      5.865833e+00  3.750180e+00    9.747263e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  1.279000e+03         1.279000e+03          1.279000e+03  1.279000e+03   
mean   7.777637e-17        -7.916524e-17         -8.333183e-18  6.007530e-15   
std    1.000391e+00         1.000391e+00          1.000391e+00  1.000391e+00   
min   -1.510855e+00        -1.421700e+00         -1.237870e+00 -3.527628e+00   
25%   -3.598354e-01        -7.555316e-01         -7.516929e-01 -6.035913e-01   
50%   -1.812288e-01        -1.845301e-01         -2.655158e-01  9.769017e-03   
75%    3.706812e-02         4.816384e-01          4.941359e-01  5.728972e-01   
max    1.037640e+01         5.335151e+00          7.027141e+00  3.674068e+00   

                 pH     sulphates       alcohol  
count  1.279000e+03  1.279000e+03  1.279000e+03  
mean  -6.416551e-16  7.222092e-17 -7.645695e-16  
std    1.000391e+00  1.000391e+00  1.000391e+00  
min   -3.641564e+00 -1.667838e+00 -1.880160e+00  
25%   -6.506045e-01 -6.298296e-01 -8.565229e-01  
50%   -1.423011e-02 -2.261597e-01 -2.981757e-01  
75%    5.585068e-01  4.081786e-01  6.324031e-01  
max    4.440390e+00  7.731903e+00  4.168602e+00

In [87]:
X_test_red_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_test_red), columns=X_test_red.columns.values)
X_test_red_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.805556          0.835775    -1.268633       -0.084588   0.671518   
1      -0.633933          0.350751    -1.068355       -0.084588  -0.292841   
2       0.395806         -0.505174     1.184767       -0.026125  -0.026811   
3       0.681845         -0.448112    -0.066968        0.032337   0.239219   
4      -0.061856          0.921368    -0.117037       -0.376900   0.471996   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.622765             -0.256001 -0.089522  1.076303  -0.549816   
1             0.232393              1.300607  0.365364  1.567525  -0.680919   
2             0.525172              0.903825  1.034314  0.304382  -0.549816   
3            -0.157979             -0.042349  0.659702 -1.309634   0.564565   
4            -0.157979              1.086955  0.285090 -0.818411   0.302358   

    alcohol  
0  0.162323  
1 -0.908339  
2 -0.713673  
3 -0.421674  
4 -1.005671

In [88]:
X_test_red_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   3.200000e+02      3.200000e+02  3.200000e+02    3.200000e+02   
mean   -2.720046e-16     -1.026956e-16 -7.494005e-17   -1.387779e-16   
std     1.001566e+00      1.001566e+00  1.001566e+00    1.001566e+00   
min    -1.835295e+00     -2.159962e+00 -1.268633e+00   -7.861364e-01   
25%    -6.911408e-01     -8.475440e-01 -8.680777e-01   -4.353621e-01   
50%    -2.906867e-01      8.380931e-03 -1.420718e-01   -2.599749e-01   
75%     5.102214e-01      6.360592e-01  8.843503e-01   -2.612538e-02   
max     3.256192e+00      3.375019e+00  2.636778e+00    7.515522e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  3.200000e+02         3.200000e+02          3.200000e+02  3.200000e+02   
mean   4.163336e-17        -1.665335e-17         -7.771561e-17  1.062095e-13   
std    1.001566e+00         1.001566e+00          1.001566e+00  1.001566e+00   
min   -1.523230e+00        -1.231501e+00         -1.202175e+00 -2.979388e+00   
25%   -4.591097e-01        -8.411291e-01         -7.138269e-01 -6.286963e-01   
50%   -1.930796e-01        -2.555715e-01         -2.407401e-01 -2.530305e-02   
75%    2.142789e-01         6.227649e-01          3.849553e-01  6.061862e-01   
max    9.151227e+00         5.112040e+00          7.435475e+00  3.121440e+00   

                 pH     sulphates       alcohol  
count  3.200000e+02  3.200000e+02  3.200000e+02  
mean   3.633205e-15  1.137979e-16 -2.720046e-16  
std    1.001566e+00  1.001566e+00  1.001566e+00  
min   -2.572776e+00 -2.123058e+00 -1.395003e+00  
25%   -7.482367e-01 -6.153673e-01 -9.083386e-01  
50%    2.368393e-02 -2.220566e-01 -2.270086e-01  
75%    6.552553e-01  4.334611e-01  6.489871e-01  
max    2.690319e+00  6.136466e+00  3.471640e+00

#### 1.2.2.2- White wine

In [89]:
X_train_white_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_train_white), columns=X_train_white.columns.values)
X_train_white_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.181563          2.567784    -0.520425        0.125102   0.131076   
1      -1.019660         -0.759337    -0.603302        0.066489   0.131076   
2      -1.259116         -0.759337    -1.432073       -0.988543  -0.178855   
3      -2.576124         -1.297548    -0.354671       -1.066694  -0.178855   
4      -0.301291          1.540291     0.391223        0.535393   0.529560   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0            -1.609709              0.927951  0.312904 -0.184966  -0.958293   
1            -0.788518             -1.087502 -0.421648 -0.251709  -0.604462   
2             0.501927             -0.945235 -1.639284  0.282236  -1.046751   
3            -0.025982             -1.158636 -1.083406  3.819622   0.014743   
4             1.792371              2.469180  1.408115  0.282236   0.457032   

    alcohol  
0 -0.893041  
1  0.410855  
2  1.388777  
3  0.655335  
4 -1.137521

In [90]:
X_train_white_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   3.918000e+03      3.918000e+03  3.918000e+03    3.918000e+03   
mean    2.298655e-16     -1.994888e-16 -2.956061e-16    5.032558e-17   
std     1.000128e+00      1.000128e+00  1.000128e+00    1.000128e+00   
min    -3.533949e+00     -1.933615e+00 -2.758106e+00   -1.144844e+00   
25%    -6.604754e-01     -6.614804e-01 -5.204250e-01   -9.299302e-01   
50%    -6.183505e-02     -1.721979e-01 -1.889166e-01   -2.265752e-01   
75%     5.368053e-01      4.149410e-01  3.912230e-01    6.916937e-01   
max     8.798042e+00      8.047747e+00  1.099949e+01    1.159369e+01   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  3.918000e+03         3.918000e+03          3.918000e+03  3.918000e+03   
mean  -3.527324e-16        -6.619400e-17         -2.597888e-16  3.431751e-14   
std    1.000128e+00         1.000128e+00          1.000128e+00  1.000128e+00   
min   -1.507134e+00        -1.961649e+00         -3.055533e+00 -2.304351e+00   
25%   -4.445111e-01        -6.712044e-01         -7.081229e-01 -7.690710e-01   
50%   -1.345794e-01        -8.463881e-02         -1.153425e-01 -9.076843e-02   
75%    1.753522e-01         6.192399e-01          6.908387e-01  7.033419e-01   
max    1.328103e+01         1.487278e+01          7.140289e+00  1.485836e+01   

                 pH     sulphates       alcohol  
count  3.918000e+03  3.918000e+03  3.918000e+03  
mean  -9.879228e-16 -4.488497e-17  2.466407e-16  
std    1.000128e+00  1.000128e+00  1.000128e+00  
min   -3.121664e+00 -2.373619e+00 -2.033949e+00  
25%   -6.521680e-01 -6.929199e-01 -8.930407e-01  
50%   -5.147978e-02 -1.621727e-01 -1.595994e-01  
75%    6.159516e-01  5.454901e-01  7.368289e-01  
max    4.153338e+00  5.233756e+00  3.018646e+00

In [91]:
X_test_white_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_test_white), columns=X_test_white.columns.values)
X_test_white_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -1.216984         -0.219325    -0.407245       -1.050921  -0.145714   
1       0.493309         -0.324687     0.165469        1.433444   0.285379   
2       1.063406         -0.113963     0.001837       -0.927730   0.069833   
3       0.835367          4.100521    -1.634491       -0.948262   1.578659   
4       1.063406          0.412847    -0.079980       -0.763474  -0.415147   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.013740             -0.809026 -1.191671  1.090126  -0.134630   
1             0.013740              1.456933  1.668610 -0.967681  -0.303997   
2            -0.461839              0.404063 -0.399485 -0.903375  -0.388681   
3            -0.580733              0.724502 -0.048961 -0.903375   0.119421   
4            -0.996864             -0.809026 -0.925272  0.125529   1.304994   

    alcohol  
0  0.654225  
1 -1.359829  
2 -0.070834  
3 -1.037580  
4  0.895911

In [92]:
X_test_white_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   9.800000e+02      9.800000e+02  9.800000e+02    9.800000e+02   
mean    2.537653e-17     -3.588966e-16 -6.525392e-17   -1.522592e-16   
std     1.000511e+00      1.000511e+00  1.000511e+00    1.000511e+00   
min    -3.497374e+00     -1.852438e+00 -2.779920e+00   -1.133049e+00   
25%    -6.468862e-01     -6.407736e-01 -5.708780e-01   -9.071978e-01   
50%    -7.678865e-02     -1.139631e-01 -1.617961e-01   -2.296435e-01   
75%     6.073284e-01      4.128474e-01  4.927350e-01    6.121663e-01   
max     3.913894e+00      4.363926e+00  4.665370e+00    3.260787e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  9.800000e+02         9.800000e+02          9.800000e+02  9.800000e+02   
mean  -3.443957e-16        -7.975480e-17          2.356392e-16  1.770556e-14   
std    1.000511e+00         1.000511e+00          1.000511e+00  1.000511e+00   
min   -1.923973e+00        -1.888573e+00         -2.914766e+00 -2.320360e+00   
25%   -4.825055e-01        -7.590749e-01         -7.174721e-01 -7.640309e-01   
50%   -1.457139e-01        -4.570767e-02         -7.659466e-02 -1.523655e-01   
75%    2.853793e-01         6.676596e-01          6.329482e-01  7.143065e-01   
max    8.422263e+00         4.977587e+00          5.267865e+00  2.509869e+00   

                 pH     sulphates       alcohol  
count  9.800000e+02  9.800000e+02  9.800000e+02  
mean   7.757967e-16  7.069175e-17 -1.700227e-15  
std    1.000511e+00  1.000511e+00  1.000511e+00  
min   -2.703956e+00 -2.251724e+00 -2.084888e+00  
25%   -6.461488e-01 -7.274162e-01 -8.764559e-01  
50%   -6.739056e-02 -1.346299e-01 -7.083441e-02  
75%    5.756741e-01  5.428402e-01  6.542249e-01  
max    4.048224e+00  4.353609e+00  2.668279e+00

## 1.4- SVM

In the case of the simple SVM we used "linear" as the value for the kernel parameter. However, for kernel SVM you can use Gaussian, polynomial, sigmoid, or computable kernel. We will implement linear, polynomial, Gaussian, and sigmoid kernels to see which one works better for our problem.

### 1.4.1- Linear kernel
#### 1.4.1.1- Training the algorithm

We have divided the data into training and testing sets. Now is the time to train our SVM on the training data. 

#### 1.4.1.1.1- Red wine

In [96]:
#  SVC class is called to train the algorithm on the training data
red_linear_svclassifier = SVC(kernel='linear')
red_linear_svclassifier.fit(X_train_red_scaled, y_train_red)

SVC(kernel='linear')

In [97]:
accuracy_score(y_test_red, red_linear_svclassifier.predict(X_test_red_scaled))

0.953125

##### 1.4.1.1.2- White wine

In [98]:
#  SVC class is called to train the algorithm on the training data
white_linear_svclassifier = SVC(kernel='linear')
white_linear_svclassifier.fit(X_train_white_scaled, y_train_white)

SVC(kernel='linear')

In [99]:
accuracy_score(y_test_white, white_linear_svclassifier.predict(X_test_white_scaled))

0.9275510204081633

#### 1.4.1.2- Making predictions

##### 1.4.1.2.1- Red wine

In [100]:
y_pred_red_linear = red_linear_svclassifier.predict(X_test_red_scaled)

##### 1.4.1.2.2- White wine

In [101]:
y_pred_white_linear = white_linear_svclassifier.predict(X_test_white_scaled)

#### 1.4.1.3- Evaluating the algorithm

##### 1.4.1.3.1- Red wine

In [103]:
print(confusion_matrix(y_test_red, y_pred_red_linear))
print(classification_report(y_test_red, y_pred_red_linear))
print(accuracy_score(y_test_red, y_pred_red_linear))

[[  0   0   2]
 [  0   0  13]
 [  0   0 305]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00         2
         low       0.00      0.00      0.00        13
      medium       0.95      1.00      0.98       305

    accuracy                           0.95       320
   macro avg       0.32      0.33      0.33       320
weighted avg       0.91      0.95      0.93       320

0.953125


c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##### 1.4.1.3.2- White wine

In [104]:
print(confusion_matrix(y_test_white, y_pred_white_linear))
print(classification_report(y_test_white, y_pred_white_linear))
print(accuracy_score(y_test_white, y_pred_white_linear))

[[  0   0  30]
 [  0   0  41]
 [  0   0 909]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00        30
         low       0.00      0.00      0.00        41
      medium       0.93      1.00      0.96       909

    accuracy                           0.93       980
   macro avg       0.31      0.33      0.32       980
weighted avg       0.86      0.93      0.89       980

0.9275510204081633


### 1.4.2- Polynomial kernel

#### 1.4.2.1- Training the algorithm

##### 1.4.2.1.1- Red wine

In [105]:
red_poly_svclassifier = SVC(kernel='poly', degree=8)
red_poly_svclassifier.fit(X_train_red_scaled, y_train_red)

SVC(degree=8, kernel='poly')

##### 1.4.2.1.2- White wine

In [106]:
white_poly_svclassifier = SVC(kernel='poly', degree=8)
white_poly_svclassifier.fit(X_train_white_scaled, y_train_white)

SVC(degree=8, kernel='poly')

#### 1.4.2.2- Making predictions

##### 1.4.2.2.1- Red wine

In [107]:
y_pred_red_poly = red_poly_svclassifier.predict(X_test_red_scaled)

##### 1.4.2.2.2- White wine

In [108]:
y_pred_white_poly = white_poly_svclassifier.predict(X_test_white_scaled)

#### 1.4.2.3- Evaluating the algorithm

##### 1.4.2.3.1- Red wine

In [109]:
print(confusion_matrix(y_test_red, y_pred_red_poly))
print(classification_report(y_test_red, y_pred_red_poly))
print(accuracy_score(y_test_red, y_pred_red_poly))

[[  0   0   2]
 [  0   3  10]
 [  2   6 297]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00         2
         low       0.33      0.23      0.27        13
      medium       0.96      0.97      0.97       305

    accuracy                           0.94       320
   macro avg       0.43      0.40      0.41       320
weighted avg       0.93      0.94      0.93       320

0.9375


##### 1.4.2.3.2- White wine

In [110]:
print(confusion_matrix(y_test_white, y_pred_white_poly))
print(classification_report(y_test_white, y_pred_white_poly))
print(accuracy_score(y_test_white, y_pred_white_poly))

[[  7   0  23]
 [  1   5  35]
 [  8   9 892]]
              precision    recall  f1-score   support

        high       0.44      0.23      0.30        30
         low       0.36      0.12      0.18        41
      medium       0.94      0.98      0.96       909

    accuracy                           0.92       980
   macro avg       0.58      0.45      0.48       980
weighted avg       0.90      0.92      0.91       980

0.9224489795918367


### 1.4.3- Gaussian kernel

#### 1.4.3.1- Training the algorithm

##### 1.4.3.1.1- Red wine

In [111]:
red_gaussian_svclassifier = SVC(kernel='rbf')
red_gaussian_svclassifier.fit(X_train_red_scaled, y_train_red)

SVC()

##### 1.4.3.1.2- White wine

In [112]:
white_gaussian_svclassifier = SVC(kernel='rbf')
white_gaussian_svclassifier.fit(X_train_white_scaled, y_train_white)

SVC()

#### 1.4.3.2- Making prediction

##### 1.4.3.2.1- Red wine

In [113]:
y_pred_red_gaussian= red_gaussian_svclassifier.predict(X_test_red_scaled)

##### 1.4.3.2.2- White wine

In [114]:
y_pred_white_gaussian= white_gaussian_svclassifier.predict(X_test_white_scaled)

#### 1.4.3.3- Evaluating the algorithm

##### 1.4.3.3.1- Red wine

In [115]:
print(confusion_matrix(y_test_red, y_pred_red_gaussian))
print(classification_report(y_test_red, y_pred_red_gaussian))
print(accuracy_score(y_test_red, y_pred_red_gaussian))

[[  0   0   2]
 [  0   0  13]
 [  0   0 305]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00         2
         low       0.00      0.00      0.00        13
      medium       0.95      1.00      0.98       305

    accuracy                           0.95       320
   macro avg       0.32      0.33      0.33       320
weighted avg       0.91      0.95      0.93       320

0.953125


c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##### 1.4.3.3.2- White wine

In [117]:
print(confusion_matrix(y_test_white, y_pred_white_gaussian))
print(classification_report(y_test_white, y_pred_white_gaussian))
print(accuracy_score(y_test_white, y_pred_white_gaussian))

[[  0   0  30]
 [  0   0  41]
 [  0   1 908]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00        30
         low       0.00      0.00      0.00        41
      medium       0.93      1.00      0.96       909

    accuracy                           0.93       980
   macro avg       0.31      0.33      0.32       980
weighted avg       0.86      0.93      0.89       980

0.926530612244898


### 1.4.4- Sigmoid kernel

#### 1.4.4.1- Training the algorithm

##### 1.4.4.1.1- Red wine

In [118]:
red_sigmoid_svclassifier = SVC(kernel='sigmoid')
red_sigmoid_svclassifier.fit(X_train_red_scaled, y_train_red)

SVC(kernel='sigmoid')

##### 1.4.4.1.2- White wine

In [119]:
white_sigmoid_svclassifier = SVC(kernel='sigmoid')
white_sigmoid_svclassifier.fit(X_train_white_scaled, y_train_white)

SVC(kernel='sigmoid')

#### 1.4.4.2- Making prediction

##### 1.4.4.2.1- Red wine

In [120]:
y_pred_red_sigmoid= red_sigmoid_svclassifier.predict(X_test_red_scaled)

##### 1.4.4.2.2- White wine

In [121]:
y_pred_white_sigmoid= red_sigmoid_svclassifier.predict(X_test_white_scaled)

#### 1.4.4.3- Evaluating the algorithm

##### 1.4.4.3.1- Red wine

In [122]:
print(confusion_matrix(y_test_red, y_pred_red_sigmoid))
print(classification_report(y_test_red, y_pred_red_sigmoid))
print(accuracy_score(y_test_red, y_pred_red_sigmoid))

[[  0   0   2]
 [  0   1  12]
 [  0   1 304]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00         2
         low       0.50      0.08      0.13        13
      medium       0.96      1.00      0.98       305

    accuracy                           0.95       320
   macro avg       0.49      0.36      0.37       320
weighted avg       0.93      0.95      0.94       320

0.953125


c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##### 1.4.4.3.2- White wine

In [123]:
print(confusion_matrix(y_test_white, y_pred_white_sigmoid))
print(classification_report(y_test_white, y_pred_white_sigmoid))
print(accuracy_score(y_test_white, y_pred_white_sigmoid))

[[  0   0  30]
 [  0   1  40]
 [  4   3 902]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00        30
         low       0.25      0.02      0.04        41
      medium       0.93      0.99      0.96       909

    accuracy                           0.92       980
   macro avg       0.39      0.34      0.33       980
weighted avg       0.87      0.92      0.89       980

0.9214285714285714


## 1.5- Decision Tree

A decision tree is one of most frequently and widely used supervised machine learning algorithms that can perform both regression and classification tasks. The intuition behind the decision tree algorithm is simple, yet also very powerful.

For each attribute in the dataset, the decision tree algorithm forms a node, where the most important attribute is placed at the root node. For evaluation we start at the root node and work our way down the tree by following the corresponding node that meets our condition or "decision". This process continues until a leaf node is reached, which contains the prediction or the outcome of the decision tree.

There are several advantages of using decision treess for predictive analysis:

1- Decision trees can be used to predict both continuous and discrete values i.e. they work well for both regression and classification tasks.

2- They require relatively less effort for training the algorithm.

3- They can be used to classify non-linearly separable data.

4- They're very fast and efficient compared to KNN and other classification algorithms.

### 1.5.1- Training the algorithm

#### 1.5.1.1- Red wine

In [124]:
red_tree_classifier = DecisionTreeClassifier()
red_tree_classifier.fit(X_train_red_scaled, y_train_red)

DecisionTreeClassifier()

#### 1.5.1.2- White wine

In [125]:
white_tree_classifier = DecisionTreeClassifier()
white_tree_classifier.fit(X_train_white_scaled, y_train_white)

DecisionTreeClassifier()

### 1.5.2- Making prediction

#### 1.5.2.1- Red wine

In [126]:
y_pred_red_tree = red_tree_classifier.predict(X_test_red_scaled)

In [127]:
df=pd.DataFrame({'Actual':y_test_red, 'Predicted':y_pred_red_tree})
df

Actual Predicted
31    medium    medium
883   medium    medium
592   medium    medium
552   medium    medium
360   medium    medium
...      ...       ...
734   medium    medium
1224  medium    medium
1187  medium    medium
1183  medium    medium
1563  medium    medium

[320 rows x 2 columns]

#### 1.5.2.2- White wine

In [128]:
y_pred_white_tree = white_tree_classifier.predict(X_test_white_scaled)

In [129]:
df=pd.DataFrame({'Actual':y_test_white, 'Predicted':y_pred_white_tree})
df

Actual Predicted
4647  medium    medium
1397  medium    medium
995   medium    medium
23    medium       low
616   medium    medium
...      ...       ...
1080  medium    medium
2670  medium    medium
2044  medium    medium
1724  medium    medium
4701  medium    medium

[980 rows x 2 columns]

### 1.5.3-  Evaluating the algorithm

#### 1.5.3.1- Red wine

In [130]:
print(confusion_matrix(y_test_red, y_pred_red_tree))
print(classification_report(y_test_red, y_pred_red_tree))
print(accuracy_score(y_test_red, y_pred_red_tree))

[[  0   0   2]
 [  0   3  10]
 [  8  12 285]]
              precision    recall  f1-score   support

        high       0.00      0.00      0.00         2
         low       0.20      0.23      0.21        13
      medium       0.96      0.93      0.95       305

    accuracy                           0.90       320
   macro avg       0.39      0.39      0.39       320
weighted avg       0.92      0.90      0.91       320

0.9


#### 1.5.3.2- White wine

In [131]:
print(confusion_matrix(y_test_white, y_pred_white_tree))
print(classification_report(y_test_white, y_pred_white_tree))
print(accuracy_score(y_test_white, y_pred_white_tree))

[[  9   1  20]
 [  2  13  26]
 [ 32  30 847]]
              precision    recall  f1-score   support

        high       0.21      0.30      0.25        30
         low       0.30      0.32      0.31        41
      medium       0.95      0.93      0.94       909

    accuracy                           0.89       980
   macro avg       0.48      0.52      0.50       980
weighted avg       0.90      0.89      0.89       980

0.886734693877551


## 1.6- Random Forest

### 1.6.1- Red wine


In [132]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_red_scaled, y_train_red)
print(accuracy_score(y_test_red, rf_clf.predict(X_test_red_scaled)))

0.95625


### 1.6.1- White wine

In [133]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train_white_scaled, y_train_white)
print(accuracy_score(y_test_white, rf_clf.predict(X_test_white_scaled)))

0.9346938775510204


## 1.7- K-Means

### 1.7.1- Red wine

In [80]:
X_kmeans = X_train_red[['PCA_1', 'PCA_2', 'PCA_3']]

kmeans = KMeans(n_clusters= 3, random_state=0, init='k-means++').fit(X_kmeans)
y_kmeans= kmeans.fit_predict(X_kmeans)

print('K-Means cluster center 1: ' + str(kmeans.cluster_centers_[:,0]))
print('K-Means cluster center 2: ' + str(kmeans.cluster_centers_[:,1]))
print('K-Means cluster center 3: ' + str(kmeans.cluster_centers_[:,2]))

KeyError: "None of [Index(['PCA_1', 'PCA_2', 'PCA_3'], dtype='object')] are in the [columns]"

### 1.7.2- White wine

# 2- Low alcohol vs high alcohol content

## 2.1- Exploratory data analysis

### 2.1.1- Red wine

In [135]:
# Read data with read_csv method of the pandas library.
alcohol_bankdata_red = pd.read_csv("data/new_format/winequality-red-alcohol-content.csv", sep = ',')
# see the rows and columns of the data
alcohol_bankdata_red.shape

(1599, 11)

In [137]:
# get a feel of how our dataset actually looks
alcohol_bankdata_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

  alcohol content  
0             low  
1             low  
2             low  
3             low  
4             low

In [138]:
# view some basic statistical details like percentile, mean, std etc.
alcohol_bankdata_red.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates  
count  1599.000000  1599.000000  
mean      3.311113     0.658149  
std       0.154386     0.169507  
min       2.740000     0.330000  
25%       3.210000     0.550000  
50%       3.310000     0.620000  
75%       3.400000     0.730000  
max       4.010000     2.000000

### 2.1.2- White wine

In [139]:
# Read data with read_csv method of the pandas library.
alcohol_bankdata_white = pd.read_csv("data/new_format/winequality-white-alcohol-content.csv", sep = ',')
# see the rows and columns of the data
alcohol_bankdata_white.shape

(4898, 11)

In [140]:
# get a feel of how our dataset actually looks
alcohol_bankdata_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

  alcohol content  
0             low  
1             low  
2             low  
3             low  
4             low

In [141]:
# view some basic statistical details like mean, std etc.
alcohol_bankdata_white.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates  
count  4898.000000  4898.000000  
mean      3.188267     0.489847  
std       0.151001     0.114126  
min       2.720000     0.220000  
25%       3.090000     0.410000  
50%       3.180000     0.470000  
75%       3.280000     0.550000  
max       3.820000     1.080000

## 2.2- Data preprocessing

### 2.2.1- Split dataset in train and test

#### 2.2.1.1- Red wine

In [148]:
# In the first line of the script above, all the columns of the bankdata dataframe 
#are being stored in the X variable except the "quality" column, which is the label column. 
#The drop() method drops this column.
X_alcohol_red = alcohol_bankdata_red.drop('alcohol content', axis=1)
y_alcohol_red = alcohol_bankdata_red['alcohol content']

In [143]:
# divide data into training and test sets.
X_train_alcohol_red, X_test_alcohol_red, y_train_alcohol_red, y_test_alcohol_red = train_test_split(X_alcohol_red, y_alcohol_red, test_size = 0.20)
X_train_alcohol_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
885             8.9              0.75         0.14             2.5      0.086   
558            10.9              0.53         0.49             4.6      0.118   
423            10.5              0.24         0.47             2.1      0.066   
171             8.0              0.42         0.17             2.0      0.073   
1570            6.4              0.36         0.53             2.2      0.230   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  
885                   9.0                  30.0  0.99824  3.34       0.64  
558                  10.0                  17.0  1.00020  3.07       0.56  
423                   6.0                  24.0  0.99780  3.15       0.90  
171                   6.0                  18.0  0.99720  3.29       0.61  
1570                 19.0                  35.0  0.99340  3.37       0.93

In [144]:
y_train_alcohol_red.head()

885     high
558     high
423     high
171      low
1570    high
Name: alcohol content, dtype: object

#### 2.2.1.2- White wine

In [149]:
# In the first line of the script above, all the columns of the bankdata dataframe 
#are being stored in the X variable except the "quality" column, which is the label column. 
#The drop() method drops this column.
X_alcohol_white = alcohol_bankdata_white.drop('alcohol content', axis=1)
y_alcohol_white = alcohol_bankdata_white['alcohol content']

In [146]:
# divide data into training and test sets.
X_train_alcohol_white, X_test_alcohol_white, y_train_alcohol_white, y_test_alcohol_white = train_test_split(X_alcohol_white, y_alcohol_white, test_size = 0.20)
X_train_alcohol_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3451            6.6              0.21         0.29            5.35      0.029   
1089            7.0              0.17         0.33            4.00      0.034   
693             5.9              0.37         0.14            6.30      0.036   
1738            7.5              0.15         0.38            1.80      0.054   
4239            5.7              0.28         0.36            1.80      0.041   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  
3451                 43.0                 106.0  0.99112  2.93       0.43  
1089                 17.0                 127.0  0.99340  3.19       0.39  
693                  34.0                 185.0  0.99440  3.17       0.63  
1738                 19.0                 101.0  0.99460  3.24       0.44  
4239                 38.0                  90.0  0.99002  3.27       0.98

In [147]:
y_train_alcohol_white.head()

3451    high
1089    high
693      low
1738     low
4239    high
Name: alcohol content, dtype: object

### 2.2.2- Data standarization

Standarization of datasets is a common requirement for many machine learning estimators. They might behave badly if the individual features do not more or less look like standard normally distributed data: Gaussian with zero mean and unit variance.

Here we are going to use StandardScaler, that standardize features by removing the mean and scaling to unit variance. The standard score of a sample $x$ is calculated as:

$x_{scaled} = \dfrac{x - \mu}{\sigma}$

where $\mu$ is the mean of the training samples and $\sigma$ is the standard deviation of the training samples.

#### 2.2.2.1- Red wine

In [150]:
X_train_alcohol_red_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_train_alcohol_red), columns=X_train_alcohol_red.columns.values)
X_train_alcohol_red_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.345752          1.232888    -0.665878       -0.026318  -0.037008   
1       1.499613          0.010836     1.142643        1.422223   0.627612   
2       1.268841         -1.600051     1.039299       -0.302231  -0.452395   
3      -0.173485         -0.600190    -0.510862       -0.371209  -0.307010   
4      -1.096573         -0.933477     1.349331       -0.233253   2.953780   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  
0            -0.665879             -0.505725  0.796580  0.180564  -0.090055  
1            -0.569292             -0.909698  1.836225 -1.547657  -0.577847  
2            -0.955642             -0.692174  0.563190 -1.035591   1.495271  
3            -0.955642             -0.878623  0.244931 -0.139477  -0.272977  
4             0.299995             -0.350351 -1.770707  0.372589   1.678194

In [151]:
X_train_alcohol_red_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   1.279000e+03      1.279000e+03  1.279000e+03    1.279000e+03   
mean    1.111091e-15      1.930521e-16 -4.027705e-17    2.722173e-16   
std     1.000391e+00      1.000391e+00  1.000391e+00    1.000391e+00   
min    -2.135048e+00     -2.266624e+00 -1.389287e+00   -1.129969e+00   
25%    -6.927222e-01     -7.668334e-01 -9.242384e-01   -4.401873e-01   
50%    -2.311781e-01     -4.471186e-02 -9.748600e-02   -2.332529e-01   
75%     5.188312e-01      6.079749e-01  7.809384e-01    4.265967e-02   
max     4.384264e+00      5.843356e+00  3.777916e+00    8.940840e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  1.279000e+03         1.279000e+03          1.279000e+03  1.279000e+03   
mean   1.881910e-16         6.249887e-17         -7.777637e-17 -3.859097e-14   
std    1.000391e+00         1.000391e+00          1.000391e+00  1.000391e+00   
min   -1.573941e+00        -1.438579e+00         -1.251521e+00 -3.537043e+00   
25%   -3.693179e-01        -8.107606e-01         -7.543236e-01 -6.037584e-01   
50%   -1.823937e-01        -1.829422e-01         -2.571265e-01  6.237439e-03   
75%    4.606934e-02         5.897573e-01          5.197440e-01  5.631901e-01   
max    1.086691e+01         5.419130e+00          7.542653e+00  3.687430e+00   

                 pH     sulphates  
count  1.279000e+03  1.279000e+03  
mean  -3.083278e-15 -1.777746e-16  
std    1.000391e+00  1.000391e+00  
min   -3.659927e+00 -1.980251e+00  
25%   -6.515423e-01 -6.388215e-01  
50%   -1.146042e-02 -2.120029e-01  
75%    5.646133e-01  3.977379e-01  
max    4.469113e+00  8.202420e+00

In [152]:
X_test_alcohol_red_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_test_alcohol_red), columns=X_test_alcohol_red.columns.values)
X_test_alcohol_red_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.280286         -0.153874     0.253873       -0.438174  -0.052085   
1      -0.110523          1.447418    -1.402025       -0.276309   0.065954   
2      -1.355452         -0.153874    -1.402025       -0.923769  -0.689496   
3      -0.959338          0.989906    -1.000595        0.978146  -0.453418   
4      -0.053935          1.847741    -0.699523       -0.033511   0.160386   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  
0            -0.073516              2.693521  0.010355 -0.739965  -0.643422  
1            -0.257667             -0.597457  0.538814  0.420430  -1.119419  
2            -0.073516             -0.597457 -1.215672  0.352171  -1.172307  
3            -0.718045             -0.878737 -1.818117  0.829981  -0.802088  
4            -0.257667              0.190128  0.242877  0.352171  -0.696311

In [153]:
X_test_alcohol_red_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   3.200000e+02      3.200000e+02  3.200000e+02    3.200000e+02   
mean    3.941292e-16      5.218048e-16  1.554312e-16   -5.828671e-17   
std     1.001566e+00      1.001566e+00  1.001566e+00    1.001566e+00   
min    -1.864742e+00     -1.926734e+00 -1.402025e+00   -1.004702e+00   
25%    -7.329876e-01     -7.829534e-01 -9.504162e-01   -5.191064e-01   
50%    -2.236983e-01     -9.668518e-02 -2.211000e-02   -2.763088e-01   
75%     5.119419e-01      6.467720e-01  8.058388e-01    4.742141e-02   
max     4.076967e+00      3.763573e+00  2.411558e+00    9.111867e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  3.200000e+02         3.200000e+02          3.200000e+02  3.200000e+02   
mean   8.326673e-17        -1.665335e-17         -2.081668e-17 -4.584111e-14   
std    1.001566e+00         1.001566e+00          1.001566e+00  1.001566e+00   
min   -1.751849e+00        -1.178422e+00         -1.160017e+00 -3.244959e+00   
25%   -3.825944e-01        -8.101201e-01         -7.662247e-01 -5.986955e-01   
50%   -1.701239e-01        -2.576674e-01         -2.739845e-01 -1.342618e-02   
75%    1.131700e-01         4.789362e-01          3.870239e-01  5.916604e-01   
max    8.918891e+00         4.806482e+00          6.490803e+00  3.392498e+00   

                 pH     sulphates  
count  3.200000e+02  3.200000e+02  
mean  -5.967449e-17 -3.302913e-16  
std    1.001566e+00  1.001566e+00  
min   -2.651205e+00 -1.489639e+00  
25%   -6.717068e-01 -5.905336e-01  
50%    1.087871e-02 -2.732024e-01  
75%    5.569471e-01  4.143486e-01  
max    2.604704e+00  6.760973e+00

#### 2.2.2.2- White wine

In [154]:
X_train_alcohol_white_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_train_alcohol_white), columns=X_train_alcohol_white.columns.values)
X_train_alcohol_white_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.316513         -0.670103    -0.369193       -0.203457  -0.777965   
1       0.161344         -1.066325    -0.040686       -0.469891  -0.545880   
2      -1.152763          0.914784    -1.601092       -0.015966  -0.453046   
3       0.758665         -1.264436     0.369947       -0.904081   0.382461   
4      -1.391691          0.023285     0.205694       -0.904081  -0.220961   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  
0             0.449297             -0.770480 -0.972769 -1.687436  -0.522860  
1            -1.079801             -0.279599 -0.211232  0.018844  -0.874379  
2            -0.080006              1.076167  0.122776 -0.112409   1.234736  
3            -0.962178             -0.887357  0.189578  0.346974  -0.434980  
4             0.155239             -1.144485 -1.340178  0.543853   4.310529

In [155]:
X_train_alcohol_white_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   3.918000e+03      3.918000e+03  3.918000e+03    3.918000e+03   
mean    8.782040e-16      4.134858e-16 -4.814934e-16   -3.627069e-18   
std     1.000128e+00      1.000128e+00  1.000128e+00    1.000128e+00   
min    -3.661512e+00     -1.957825e+00 -2.750865e+00   -1.140912e+00   
25%    -6.749058e-01     -6.701035e-01 -5.334458e-01   -9.238168e-01   
50%    -7.758467e-02     -1.748261e-01 -1.228126e-01   -2.478623e-01   
75%     6.093347e-01      4.195068e-01  4.520738e-01    6.846588e-01   
max     4.581520e+00      8.145834e+00  1.088216e+01    1.172689e+01   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  3.918000e+03         3.918000e+03          3.918000e+03  3.918000e+03   
mean  -3.300632e-16         1.809000e-16         -1.659384e-16 -4.389025e-14   
std    1.000128e+00         1.000128e+00          1.000128e+00  1.000128e+00   
min   -1.706305e+00        -1.961972e+00         -2.827505e+00 -2.312140e+00   
25%   -4.530457e-01        -7.269322e-01         -7.237298e-01 -7.656846e-01   
50%   -1.281266e-01        -8.000637e-02         -9.259725e-02 -9.432905e-02   
75%    1.967925e-01         6.257309e-01          6.787870e-01  6.972693e-01   
max    1.393623e+01         1.491691e+01          7.036863e+00  1.501284e+01   

                 pH     sulphates  
count  3.918000e+03  3.918000e+03  
mean   2.024811e-15 -6.438047e-17  
std    1.000128e+00  1.000128e+00  
min   -3.065585e+00 -2.368336e+00  
25%   -7.030440e-01 -6.986197e-01  
50%   -4.678250e-02 -1.713409e-01  
75%    6.094790e-01  5.316974e-01  
max    4.087665e+00  5.189327e+00

In [156]:
X_test_alcohol_white_scaled = pd.DataFrame(preprocessing.StandardScaler().fit_transform(X_test_alcohol_white), columns=X_test_alcohol_white.columns.values)
X_test_alcohol_white_scaled.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.016323         -1.604953    -0.179346       -0.242342  -0.035649   
1       0.328936         -0.505719     0.499262       -0.949640  -0.600543   
2      -0.937015          0.593515    -0.348998       -0.065517   0.007804   
3       1.709973          1.093167     3.128867        0.818605  -0.035649   
4      -0.476669         -1.105301    -0.094520       -0.792462   0.094711   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  
0            -0.358523             -0.386973  0.064751  1.495826  -0.270792  
1            -1.357852             -1.720593 -1.413187  0.393846  -0.790797  
2            -0.358523             -0.047506  0.205826  1.977942   0.682551  
3            -0.123387              0.801162  1.206793 -0.708135   0.682551  
4             0.346886              1.552839 -0.069607  2.115690   0.075878

In [157]:
X_test_alcohol_white_scaled.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   9.800000e+02      9.800000e+02  9.800000e+02    9.800000e+02   
mean    6.706653e-17     -2.782355e-16  1.522592e-16    1.232574e-16   
std     1.000511e+00      1.000511e+00  1.000511e+00    1.000511e+00   
min    -2.778398e+00     -2.004674e+00 -2.808952e+00   -1.126464e+00   
25%    -5.917558e-01     -7.055797e-01 -5.186504e-01   -9.496395e-01   
50%    -1.314099e-01     -1.059976e-01 -9.452039e-02   -2.325181e-01   
75%     5.591088e-01      4.935846e-01  4.144356e-01    7.203692e-01   
max     8.500074e+00      5.340207e+00  5.673647e+00    3.854091e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  9.800000e+02         9.800000e+02          9.800000e+02  9.800000e+02   
mean  -1.812609e-16        -1.740105e-16         -2.247635e-16 -1.247075e-15   
std    1.000511e+00         1.000511e+00          1.000511e+00  1.000511e+00   
min   -1.426157e+00        -1.828124e+00         -3.078461e+00 -2.279796e+00   
25%   -4.267297e-01        -6.524431e-01         -6.779443e-01 -7.951403e-01   
50%   -1.660096e-01        -1.233866e-01         -9.600088e-02 -1.031969e-01   
75%    1.816173e-01         5.820222e-01          6.799237e-01  6.693614e-01   
max    9.784809e+00         6.078332e+00          3.298669e+00  3.003831e+00   

                 pH     sulphates  
count  9.800000e+02  9.800000e+02  
mean  -1.196322e-15 -1.178196e-16  
std    1.000511e+00  1.000511e+00  
min   -2.361106e+00 -2.090810e+00  
25%   -7.081349e-01 -7.041294e-01  
50%   -8.827088e-02 -9.745674e-02  
75%    6.004669e-01  4.442152e-01  
max    4.319651e+00  4.409254e+00

## 2.3- SVM

In the case of the simple SVM we used "linear" as the value for the kernel parameter. However, for kernel SVM you can use Gaussian, polynomial, sigmoid, or computable kernel. We will implement linear, polynomial, Gaussian, and sigmoid kernels to see which one works better for our problem.

### 2.3.1- Linear kernel
#### 2.3.1.1- Training the algorithm

We have divided the data into training and testing sets. Now is the time to train our SVM on the training data. 

#### 2.3.1.1.1- Red wine

In [158]:
#  SVC class is called to train the algorithm on the training data
alcohol_red_linear_svclassifier = SVC(kernel='linear')
alcohol_red_linear_svclassifier.fit(X_train_alcohol_red_scaled, y_train_alcohol_red)

SVC(kernel='linear')

In [159]:
accuracy_score(y_test_alcohol_red, alcohol_red_linear_svclassifier.predict(X_test_alcohol_red_scaled))

0.828125

#### 2.3.1.1.2- White wine

In [160]:
#  SVC class is called to train the algorithm on the training data
alcohol_white_linear_svclassifier = SVC(kernel='linear')
alcohol_white_linear_svclassifier.fit(X_train_alcohol_white_scaled, y_train_alcohol_white)

SVC(kernel='linear')

In [161]:
accuracy_score(y_test_alcohol_white, alcohol_white_linear_svclassifier.predict(X_test_alcohol_white_scaled))

0.9377551020408164

#### 2.3.1.2- Making predictions

##### 2.3.1.2.1- Red wine

In [165]:
y_pred_alcohol_red_linear = alcohol_red_linear_svclassifier.predict(X_test_alcohol_red_scaled)

##### 2.3.1.2.2- White wine

In [164]:
y_pred_alcohol_white_linear = alcohol_white_linear_svclassifier.predict(X_test_alcohol_white_scaled)

#### 2.3.1.3- Evaluating the algorithm

##### 2.3.1.3.1- Red wine

In [166]:
print(confusion_matrix(y_test_alcohol_red, y_pred_alcohol_red_linear))
print(classification_report(y_test_alcohol_red, y_pred_alcohol_red_linear))
print(accuracy_score(y_test_alcohol_red, y_pred_alcohol_red_linear))

[[106  38]
 [ 17 159]]
              precision    recall  f1-score   support

        high       0.86      0.74      0.79       144
         low       0.81      0.90      0.85       176

    accuracy                           0.83       320
   macro avg       0.83      0.82      0.82       320
weighted avg       0.83      0.83      0.83       320

0.828125


##### 2.3.1.3.2- White wine

In [167]:
print(confusion_matrix(y_test_alcohol_white, y_pred_alcohol_white_linear))
print(classification_report(y_test_alcohol_white, y_pred_alcohol_white_linear))
print(accuracy_score(y_test_alcohol_white, y_pred_alcohol_white_linear))

[[392  37]
 [ 24 527]]
              precision    recall  f1-score   support

        high       0.94      0.91      0.93       429
         low       0.93      0.96      0.95       551

    accuracy                           0.94       980
   macro avg       0.94      0.94      0.94       980
weighted avg       0.94      0.94      0.94       980

0.9377551020408164


### 2.3.2- Polynomial kernel

#### 2.3.2.1- Training the algorithm

##### 2.3.2.1.1- Red wine

In [168]:
red_alcohol_poly_svclassifier = SVC(kernel='poly', degree=8)
red_alcohol_poly_svclassifier.fit(X_train_alcohol_red_scaled, y_train_alcohol_red)

SVC(degree=8, kernel='poly')

##### 2.3.2.1.2- White wine

In [169]:
white_alcohol_poly_svclassifier = SVC(kernel='poly', degree=8)
white_alcohol_poly_svclassifier.fit(X_train_alcohol_white_scaled, y_train_alcohol_white)

SVC(degree=8, kernel='poly')

#### 2.3.2.2- Making predictions

##### 2.3.2.2.1- Red wine

In [170]:
y_pred_alcohol_red_poly = red_alcohol_poly_svclassifier.predict(X_test_alcohol_red_scaled)

##### 2.3.2.2.2- White wine

In [171]:
y_pred_alcohol_white_poly = white_alcohol_poly_svclassifier.predict(X_test_alcohol_white_scaled)

#### 2.3.2.3- Evaluating the algorithm

##### 2.3.2.3.1- Red wine

In [172]:
print(confusion_matrix(y_test_alcohol_red, y_pred_alcohol_red_poly))
print(classification_report(y_test_alcohol_red, y_pred_alcohol_red_poly))
print(accuracy_score(y_test_alcohol_red, y_pred_alcohol_red_poly))

[[ 41 103]
 [ 14 162]]
              precision    recall  f1-score   support

        high       0.75      0.28      0.41       144
         low       0.61      0.92      0.73       176

    accuracy                           0.63       320
   macro avg       0.68      0.60      0.57       320
weighted avg       0.67      0.63      0.59       320

0.634375


##### 2..2.3.2- White wine

In [174]:
print(confusion_matrix(y_test_alcohol_white, y_pred_alcohol_white_poly))
print(classification_report(y_test_alcohol_white, y_pred_alcohol_white_poly))
print(accuracy_score(y_test_alcohol_white, y_pred_alcohol_white_poly))

[[370  59]
 [151 400]]
              precision    recall  f1-score   support

        high       0.71      0.86      0.78       429
         low       0.87      0.73      0.79       551

    accuracy                           0.79       980
   macro avg       0.79      0.79      0.79       980
weighted avg       0.80      0.79      0.79       980

0.7857142857142857


### 2.3.3- Gaussian kernel

#### 2.3.3.1- Training the algorithm

##### 2.3.3.1.1- Red wine

In [175]:
red_alcohol_gaussian_svclassifier = SVC(kernel='rbf')
red_alcohol_gaussian_svclassifier.fit(X_train_alcohol_red_scaled, y_train_alcohol_red)

SVC()

##### 2.3.3.1.2- White wine

In [177]:
white_alcohol_gaussian_svclassifier = SVC(kernel='rbf')
white_alcohol_gaussian_svclassifier.fit(X_train_alcohol_white_scaled, y_train_alcohol_white)

SVC()

#### 2.3.3.2- Making prediction

##### 2.3.3.2.1- Red wine

In [178]:
y_pred_alcohol_red_gaussian= red_alcohol_gaussian_svclassifier.predict(X_test_alcohol_red_scaled)

##### 2.3.3.2.2- White wine

In [179]:
y_pred_alcohol_white_gaussian= red_alcohol_gaussian_svclassifier.predict(X_test_alcohol_white_scaled)

#### 2.3.3.3- Evaluating the algorithm

##### 2.3.3.3.1- Red wine

In [180]:
print(confusion_matrix(y_test_alcohol_red, y_pred_alcohol_red_gaussian))
print(classification_report(y_test_alcohol_red, y_pred_alcohol_red_gaussian))
print(accuracy_score(y_test_alcohol_red, y_pred_alcohol_red_gaussian))

[[111  33]
 [ 13 163]]
              precision    recall  f1-score   support

        high       0.90      0.77      0.83       144
         low       0.83      0.93      0.88       176

    accuracy                           0.86       320
   macro avg       0.86      0.85      0.85       320
weighted avg       0.86      0.86      0.85       320

0.85625


##### 2.3.3.3.2- White wine

In [181]:
print(confusion_matrix(y_test_alcohol_white, y_pred_alcohol_white_gaussian))
print(classification_report(y_test_alcohol_white, y_pred_alcohol_white_gaussian))
print(accuracy_score(y_test_alcohol_white, y_pred_alcohol_white_gaussian))

[[291 138]
 [ 95 456]]
              precision    recall  f1-score   support

        high       0.75      0.68      0.71       429
         low       0.77      0.83      0.80       551

    accuracy                           0.76       980
   macro avg       0.76      0.75      0.76       980
weighted avg       0.76      0.76      0.76       980

0.7622448979591837


### 2.3.4- Sigmoid kernel

#### 2.3.4.1- Training the algorithm

##### 2.3.4.1.1- Red wine

In [182]:
red_alcohol_sigmoid_svclassifier = SVC(kernel='sigmoid')
red_alcohol_sigmoid_svclassifier.fit(X_train_alcohol_red_scaled, y_train_alcohol_red)

SVC(kernel='sigmoid')

##### 2.3.4.1.2- White wine

In [185]:
white_alcohol_sigmoid_svclassifier = SVC(kernel='sigmoid')
white_alcohol_sigmoid_svclassifier.fit(X_train_alcohol_white_scaled, y_train_alcohol_white)

SVC(kernel='sigmoid')

#### 2.3.4.2- Making prediction

##### 2.3.4.2.1- Red wine

In [184]:
y_pred_alcohol_red_sigmoid= red_alcohol_sigmoid_svclassifier.predict(X_test_alcohol_red_scaled)

##### 2.3.4.2.2- White wine

In [186]:
y_pred_alcohol_white_sigmoid= white_alcohol_sigmoid_svclassifier.predict(X_test_alcohol_white_scaled)

#### 2.3.4.3- Evaluating the algorithm

##### 2.3.4.3.1- Red wine

In [188]:
print(confusion_matrix(y_test_alcohol_red, y_pred_alcohol_red_sigmoid))
print(classification_report(y_test_alcohol_red, y_pred_alcohol_red_sigmoid))
print(accuracy_score(y_test_alcohol_red, y_pred_alcohol_red_sigmoid))

[[ 94  50]
 [ 44 132]]
              precision    recall  f1-score   support

        high       0.68      0.65      0.67       144
         low       0.73      0.75      0.74       176

    accuracy                           0.71       320
   macro avg       0.70      0.70      0.70       320
weighted avg       0.71      0.71      0.71       320

0.70625


##### 2.3.4.3.2- White wine

In [189]:
print(confusion_matrix(y_test_alcohol_white, y_pred_alcohol_white_sigmoid))
print(classification_report(y_test_alcohol_white, y_pred_alcohol_white_sigmoid))
print(accuracy_score(y_test_alcohol_white, y_pred_alcohol_white_sigmoid))

[[344  85]
 [ 88 463]]
              precision    recall  f1-score   support

        high       0.80      0.80      0.80       429
         low       0.84      0.84      0.84       551

    accuracy                           0.82       980
   macro avg       0.82      0.82      0.82       980
weighted avg       0.82      0.82      0.82       980

0.823469387755102


## 2.4- Decision Tree

A decision tree is one of most frequently and widely used supervised machine learning algorithms that can perform both regression and classification tasks. The intuition behind the decision tree algorithm is simple, yet also very powerful.

For each attribute in the dataset, the decision tree algorithm forms a node, where the most important attribute is placed at the root node. For evaluation we start at the root node and work our way down the tree by following the corresponding node that meets our condition or "decision". This process continues until a leaf node is reached, which contains the prediction or the outcome of the decision tree.

There are several advantages of using decision treess for predictive analysis:

1- Decision trees can be used to predict both continuous and discrete values i.e. they work well for both regression and classification tasks.

2- They require relatively less effort for training the algorithm.

3- They can be used to classify non-linearly separable data.

4- They're very fast and efficient compared to KNN and other classification algorithms.

### 2.4.1- Training the algorithm

#### 2.4.1.1- Red wine

In [192]:
red_alcohol_tree_classifier = DecisionTreeClassifier()
red_alcohol_tree_classifier.fit(X_train_alcohol_red_scaled, y_train_alcohol_red)

DecisionTreeClassifier()

#### 2.4.2.2- White wine

In [193]:
white_alcohol_tree_classifier = DecisionTreeClassifier()
white_alcohol_tree_classifier.fit(X_train_alcohol_white_scaled, y_train_alcohol_white)

DecisionTreeClassifier()

### 2.3.2- Making prediction

#### 2.3.2.1- Red wine

In [194]:
y_pred_alcohol_red_tree = red_alcohol_tree_classifier.predict(X_test_alcohol_red_scaled)
df_alcohol = pd.DataFrame({'Actual':y_test_alcohol_red, 'Predicted':y_pred_alcohol_red_tree})
df_alcohol

Actual Predicted
188     low       low
1263    low       low
1336    low       low
1471   high      high
1361    low       low
...     ...       ...
1423   high       low
144    high      high
797    high       low
1346   high      high
63      low       low

[320 rows x 2 columns]

#### 2.4.2.2- White wine

In [195]:
y_pred_alcohol_white_tree = white_alcohol_tree_classifier.predict(X_test_alcohol_white_scaled)
df_alcohol = pd.DataFrame({'Actual':y_test_alcohol_white, 'Predicted':y_pred_alcohol_white_tree})
df_alcohol

Actual Predicted
770     low       low
491    high      high
4826   high       low
296     low       low
226     low       low
...     ...       ...
3450   high      high
3212   high      high
4488   high      high
3307   high      high
4896   high      high

[980 rows x 2 columns]

### 2.4.3-  Evaluating the algorithm

#### 2.4.3.1- Red wine

In [196]:
print(confusion_matrix(y_test_alcohol_red, y_pred_alcohol_red_tree))
print(classification_report(y_test_alcohol_red, y_pred_alcohol_red_tree))
print(accuracy_score(y_test_alcohol_red, y_pred_alcohol_red_tree))

[[107  37]
 [ 28 148]]
              precision    recall  f1-score   support

        high       0.79      0.74      0.77       144
         low       0.80      0.84      0.82       176

    accuracy                           0.80       320
   macro avg       0.80      0.79      0.79       320
weighted avg       0.80      0.80      0.80       320

0.796875


#### 2.4.3.2- White wine

In [197]:
print(confusion_matrix(y_test_alcohol_white, y_pred_alcohol_white_tree))
print(classification_report(y_test_alcohol_white, y_pred_alcohol_white_tree))
print(accuracy_score(y_test_alcohol_white, y_pred_alcohol_white_tree))

[[387  42]
 [ 42 509]]
              precision    recall  f1-score   support

        high       0.90      0.90      0.90       429
         low       0.92      0.92      0.92       551

    accuracy                           0.91       980
   macro avg       0.91      0.91      0.91       980
weighted avg       0.91      0.91      0.91       980

0.9142857142857143


## 2.5- Random Forest

### 2.5.1- Red wine


In [198]:
rf_alcohol_clf = RandomForestClassifier(random_state=0)
rf_alcohol_clf.fit(X_train_alcohol_red_scaled, y_train_alcohol_red)
print(accuracy_score(y_test_alcohol_red, rf_alcohol_clf.predict(X_test_alcohol_red_scaled)))

0.884375


In [ ]:
rf_alcohol_clf = RandomForestClassifier(random_state=0)
rf_alcohol_clf.fit(X_train_alcohol_white_scaled, y_train_alcohol_white)
print(accuracy_score(y_test_alcohol_white, rf_alcohol_clf.predict(X_test_alcohol_white_scaled)))